version: 2

project_name: unscrambler

builds:
  - id: unscrambler
    main: ./cmd/web
    binary: unscrambler
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - ghcr.io/inful/unscrambler:{{ .Tag }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --pull
    goos: linux
    goarch: amd64
  - image_templates:
      - ghcr.io/inful/unscrambler:{{ .Tag }}-arm64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
      - --pull
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: ghcr.io/inful/unscrambler:{{ .Tag }}
    image_templates:
      - ghcr.io/inful/unscrambler:{{ .Tag }}-amd64
      - ghcr.io/inful/unscrambler:{{ .Tag }}-arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: inful
    name: unscrambler
