version: 2

project_name: dagame

builds:
  - id: unscrambler
    main: ./cmd/web
    binary: unscrambler
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: explainer
    main: ./cmd/explain
    binary: explainer
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dockers_v2:
  - id: docker-unscrambler
    ids: [unscrambler]
    images:
      - ghcr.io/inful/unscrambler
    tags:
      - "{{ .Tag }}"
    dockerfile: Dockerfile

  - id: docker-explainer
    ids: [explainer]
    images:
      - ghcr.io/inful/explainer
    tags:
      - "{{ .Tag }}"
    dockerfile: Dockerfile.explainer

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: inful
    name: unscrambler
