// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package explainviews

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Explain</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css\"><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Fredoka:wght@400;600&display=swap\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = explainStyles().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</head><body><section class=\"section\"><div class=\"container\"><div class=\"columns is-centered\"><div class=\"column is-half\"><h1 class=\"title is-2\">Explain 🤔</h1><p class=\"subtitle\">One player explains a word using only emojis — others guess!</p><div class=\"card\"><div class=\"card-content\"><h2 class=\"title is-5\">Create a new game</h2><form method=\"POST\" action=\"/games\"><div class=\"field\"><label class=\"label\" for=\"rounds\">Rounds</label><div class=\"control\"><input class=\"input\" type=\"number\" id=\"rounds\" name=\"rounds\" value=\"3\" min=\"1\" max=\"10\" required></div></div><div class=\"field\"><label class=\"label\" for=\"duration\">Seconds per round</label><div class=\"control\"><input class=\"input\" type=\"number\" id=\"duration\" name=\"duration\" value=\"90\" min=\"30\" max=\"300\" required></div><p class=\"help\">Each round lasts this many seconds.</p></div><div class=\"field\"><label class=\"label\" for=\"emojis\">Emojis per round</label><div class=\"control\"><input class=\"input\" type=\"number\" id=\"emojis\" name=\"emojis\" value=\"8\" min=\"4\" max=\"20\" required></div><p class=\"help\">How many emojis the explainer gets to work with.</p></div><div class=\"field\"><div class=\"control\"><button type=\"submit\" class=\"button is-primary\">Create game</button></div></div></form></div></div></div></div></div></section></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
