// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Unscrambler - Create Game</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css\"><link rel=\"stylesheet\" href=\"/static/app.css?v=playful1\"><script src=\"https://unpkg.com/htmx.org@1.9.2\"></script><script defer src=\"/static/app.js\"></script></head><body><section class=\"section\"><div class=\"container\"><div class=\"columns is-centered\"><div class=\"column is-half\"><h1 class=\"title is-2\">Unscrambler</h1><p class=\"subtitle\">Create a new game</p><div class=\"card\"><div class=\"card-content\"><form method=\"post\" action=\"/games\"><div class=\"field\"><label class=\"label\" for=\"rounds\">Rounds</label><div class=\"control\"><input class=\"input\" type=\"number\" id=\"rounds\" name=\"rounds\" min=\"1\" max=\"10\" value=\"5\" required></div><p class=\"help\">Choose how many rounds this game should have.</p></div><div class=\"field\"><label class=\"label\" for=\"duration\">Seconds per round</label><div class=\"control\"><input class=\"input\" type=\"number\" id=\"duration\" name=\"duration\" min=\"10\" max=\"300\" value=\"60\" required></div><p class=\"help\">Each round will run for this many seconds.</p></div><div class=\"field\"><div class=\"control\"><button class=\"button is-primary\" type=\"submit\">Create game</button></div></div></form></div></div></div></div></div></section></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
